---

# - name: Configure the timezone
#   become: yes
#   template: src=timezone.tpl dest=/etc/timezone

# - name: More Configure the timezone
#   become: yes
#   file: src=/usr/share/zoneinfo/{{server.timezone}} dest=/etc/localtime state=link force=yes backup=yes

# - name: Set default system language pack
#   shell: localectl set-locale LANG="{{server.locale}}"
#   become: yes

# - name: Update RedHat
#   become: yes
#   yum: update_cache=yes
#   when: ansible_os_family == "RedHat"

- name: Install Packages
  become: yes
  yum:
    name: "{{ server.packages }}"
    state: present
  when: server.packages is defined
 
- include: configure.yml 