# - name: Install mysqldb python module
#   apt:
#     name={{ item }}
#     update_cache=yes
#   with_items:
#     - mysql-client
#     - build-essential
#     - python3-dev
#     - libmysqlclient-dev
#     - python-mysqldb
#     - python3-setuptools
#     - python-configparser
#     - python3-pip
#     - python-pip

# - name: Install Mysql driver for Python
#   shell: pip3 install --user https://github.com/davispuh/MySQL-for-Python-3/archive/2.0.tar.gz

- name: Install mysqldb python module
  apt:
    name={{ item }}
    update_cache=yes
  with_items:
    - mysql-client
    - libmysqlclient-dev

- name: Export SQL file to the server
  template:
    src=ha_injection.sql.j2
    dest=/tmp/ha_injection.sql

- name: Wait for few minutes until the database is ready
  pause:
    minutes=3
- name: Restore database with name '{{ mysql_rancher_database }}' "{{ hostvars['ha-db']['ansible_host'] }}"
  shell: mysql -u "{{ mysql_rancher_user }}" -p'{{ mysql_rancher_password }}' -h "{{ hostvars['ha-db']['ansible_host'] }}" "{{ mysql_rancher_database }}" <  /tmp/ha_injection.sql
 