---
# - name: Creating resolve file
#   copy:
#     content: |
#       nameserver 201.55.232.74
#       domain dtux.lan
#     dest: /etc/resolv.conf 
    
- name: Update apt
  become: yes
  apt: update_cache=yes

- name: Install System Packages
  become: yes
  apt: pkg={{ item }} state=latest
  with_items:
    - curl
    - wget
    - python-software-properties
    - apt-transport-https
    - ca-certificates
    - software-properties-common
    - gnupg2

- name: Configure the timezone
  become: yes
  template: src=timezone.tpl dest=/etc/timezone

- name: More Configure the timezone
  become: yes
  file: src=/usr/share/zoneinfo/{{commons.timezone}} dest=/etc/localtime state=link force=yes backup=yes

- name: Set default system language pack
  shell: locale-gen {{commons.locale}}
  become: yes

# - name: Add Kubernetes apt-key
#   apt_key:
#     url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
#     state: present

# - name: Add Kubernetes' APT repository
#   apt_repository:
#     repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
#     state: present
#     filename: 'kubernetes'

# - name: Update apt
#   become: yes
#   apt: update_cache=yes

# - name: Install Packages
#   become: yes
#   apt: pkg={{ item }} state=latest
#   with_items: "{{ commons.packages }}"
#   when: commons.packages is defined
 
#- include: configure.yml 