---
- hosts: all
  become: yes
  vars_files:
    - vars/all.yml
  vars:
    - update: true
  environment:
    APP_ENV: "{{ app.env }}"
    APP_DEBUG: "{{ app.debug }}"
    APP_SECRET: "{{ app.secret }}"
    DATABASE_URL: "{{ app.database_url }}"
    MAILER_URL: "{{ app.smtp }}"
    WKHTMLTOPDF_PATH: "/usr/bin/wkhtmltopdf"
    WKHTMLTOIMAGE_PATH: "/usr/bin/wkhtmltoimage"
    APP_NAME: "{{ app.name }}"
    APP_BUCKET: "{{ app.bucket }}"
  roles:
    - app

