---
commons:
    install: '1'
    timezone: UTC
    locale: pt_BR.UTF-8
    packages: [vim, git, docker.io, kubelet, kubeadm ]    
    user: ubuntu
    cidr: "10.244.0.0/16"

kube-virt:
    version: v0.6.3
