apiVersion: v1
kind: Pod
metadata:
  name: memory-demo-3
spec:
  containers:
  - name: memory-demo-3-ctr
    image: vish/stress
    resources:
      limits:
        memory: "1000G"
      requests:
        memory: "1000G"
    args:
      - -mem-total
      - 150M
      - -mem-alloc-size
      - 10M
      - -mem-alloc-sleep
      - 1s