---
- name: Add ppa Repository
  become: yes
  apt_repository: repo=ppa:ondrej/{{ php.ppa }}

- name: Update apt
  become: yes
  apt: update_cache=yes

- name: php | Install PHP Packages
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{  php.packages }}"
  when: php.packages is defined
  
- include: configure.yml
- include: pecl.yml
