---
- name: Install kubectl
  apt:
    name: kubectl
    state: present


- name: join cluster
  shell: "{{ hostvars['master'].join_command }} >> node_joined.txt"
  args:
    chdir: $HOME
    creates: node_joined.txt    