apiVersion: v1
kind: Pod
metadata:
  name: memory-demo-2
spec:
  containers:
  - name: memory-demo-2-ctr
    image: vish/stress
    resources:
      limits:
        memory: "50M"
      requests:
        memory: "100M"
    args:
      - -mem-total
      - 250M
      - -mem-alloc-size
      - 10M
      - -mem-alloc-sleep
      - 1s