---
- name: Installing application
  become: yes
  become_user: "www-data"
  shell:  composer install --no-ansi --no-dev --no-interaction --optimize-autoloader --no-scripts
  args:
    chdir: "{{app.path}}"
 
# - name: Updating database application
#   become: yes
#   become_user: "www-data"
#   shell:  /usr/bin/php bin/console  doctrine:schema:update --force 
#   args:
#     chdir: "{{app.path}}"

 
# - name: Migrate database application
#   become: yes
#   become_user: "www-data"
#   shell:  /usr/bin/php bin/console doctrine:migrations:migrate
#   args:
#     chdir: "{{app.path}}"
#   when: app.migration == True

# - name: Create superadmin
#   become: yes
#   become_user: "www-data"
#   shell:  /usr/bin/php bin/console fos:user:create adminuser --super-admin adminuser@super.com p@ssword
#   args:
#     chdir: "{{app.path}}"
#   when: app.load_fixtue == True        

# - name: Create admin
#   become: yes
#   become_user: "www-data"
#   shell: /usr/bin/php bin/console fos:user:create admin wesleymoraes100@hotmail.com p@ssword
#   args:
#     chdir: "{{app.path}}"
#   when: app.load_fixtue == True

# - name: Set permission
#   become: yes
#   become_user: "www-data"
#   shell:  /usr/bin/php bin/console fos:user:promote admin ROLE_ADMIN &&  /usr/bin/php bin/console fos:user:promote adminuser ROLE_ADMIN
#   args:
#     chdir: "{{app.path}}"
#   when: app.load_fixtue == True  