---
- name: Create the "{{commons.user}}" user
  user: name={{commons.user}} append=yes state=present createhome=yes shell=/bin/bash

# - name: Ensure SELinux is enforcing
#   selinux:
#     policy: targeted
#     state: disabled

- name: Creating MACAddressPolicy
  copy:
    content: |
      [Link]
      MACAddressPolicy=none
    dest: /etc/systemd/network/99-default.link
  notify: restart udevd 

- name: Allow "{{commons.user}}" to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    line: '{{commons.user}} ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

- name: Set up authorized keys for the ubuntu user
  authorized_key: user={{commons.user}} key="{{item}}"
  with_file:
    - ~/.ssh/id_rsa.pub

- name: Set up authorized keys for the root user
  authorized_key: user=root key="{{item}}"
  with_file:
    - ~/.ssh/id_rsa.pub   

